
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(64),
    name VARCHAR(64),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT unique_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64),
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT unique_categories_name UNIQUE (name)
);

-- CREATE TABLE IF NOT EXISTS events (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     annotation
-- )